env:
  DOCKER_REGISTRY_URL: 192.168.56.12:5000
  DOCKER_IMAGE_NAME: task-manager-archiver

name: Task Manager Archiver Image
run-name: ${{ gitea.actor }} is building the Archiver image
on:
  push:
    branches: [main]
    paths:
      - ".gitea/workflows/ci-archiver.yaml"
      - "services/archiver/**"
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."192.168.56.12:5000"]
              http = true
              insecure = true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 10

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: ./services/archiver
          file: ./services/archiver/Dockerfile
          provenance: mode=max
          sbom: true
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-service:
    runs-on: ubuntu-latest
    needs: build-images

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Docker Compose
        run: |
          hash=${{env.GITHUB_SHA}}
          export ARCHIVER_TAG=${hash::10} 
          echo "Using tag $ARCHIVER_TAG"
          docker compose up -d --no-deps archiver
