pipeline {
    agent
    {
        label 'docker'
    }
    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }
    stages {
        stage('Test the API') {
            agent {
                docker {
                    image 'golang:1.21-alpine'
                    args '-v go-cache:/go/pkg/mod'
                }
            }
            steps {
                sh '''
                go mod tidy
                go test -v ./...
                '''
            }
        }
        stage('Build the Monitor') {
            steps {
                sh '''
				docker build -t ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG}
				'''
            }
        }
        stage('Clean')
        {
            steps
            {
                cleanWs()
            }
        }
    }
}
