pipeline {
    agent none

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }
    stages {
        stage('Test the Monitor') {
            agent { label 'docker' }
            steps {
                script {
                    docker.image('golang:1.21-alpine').inside('-u root -v go-cache:/go/pkg/mod') {
                        sh '''
                        go mod tidy
                        go test -v ./...
                            '''
                    }
                }
            }
        }
        stage('Build the Monitor') {
            agent { label 'docker'}
            steps {
                sh '''
                # build image with current image tag
                docker build -t ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG} .
                
                # build image wuth 'latest' tag for current image
                docker tag ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG} ${REGISTRY_URL}/task-manager-monitor:latest
                
                docker push ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG}
                docker push ${REGISTRY_URL}/task-manager-monitor:latest
                '''
            }
        }
        stage('Clean') {
            agent { label 'docker' }
            steps
            {
                cleanWs()
            }
        }
    }
}