pipeline {
    agent none

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }

    stages {
        stage('Test the API') {
            agent { label 'docker' }
            steps {
                script {
                    docker.image('python:3.12-slim').inside('-u root') {
                        sh '''
                        pip install flask redis pytest
                        python3 -m pytest tests/
                        '''
                    }
                }
            }
        }

        stage('Build the API') {
            agent { label 'docker' }
            steps {
                sh '''
                # build image with current image tag
                docker build -t ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG} .
                
                # build image wuth 'latest' tag for current image
                docker tag ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG} ${REGISTRY_URL}/task-manager-api:latest
                
                docker push ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG}
                docker push ${REGISTRY_URL}/task-manager-api:latest
                '''
            }
        }

        stage('Clean') {
            agent { label 'docker' }
            steps {
                cleanWs()
            }
        }
    }
}
