pipeline {
    agent none

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }
    stages {
        stage('Test the API') {
            agent {
                docker {
                    image 'python:3.12-slim'
                    label 'docker'
                    args '-u root' 
                }
            }
            steps {
                sh '''
                pip install flask redis pytest
                python3 -m pytest tests/
                '''
            }
        }
        stage('Build the API') {
            agent { label 'docker' }
            steps {
                sh '''
				docker build -t ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG}
				'''
            }
        }
        stage('Clean') {
            agent { label 'docker' }
            steps
            {
                cleanWs()
            }
        }
    }
}
