# -*- mode: ruby -*-
# vi: set ft=ruby :

$common = <<SCRIPT
echo '* Add hosts ...'
echo '127.0.0.1       localhost' > /etc/hosts
echo '' >> /etc/hosts
echo 'ff02::1 ip6-allnodes' >> /etc/hosts
echo 'ff02::2 ip6-allrouters' >> /etc/hosts
echo '' >> /etc/hosts
echo '192.168.99.101 app.homework.lab app' >> /etc/hosts
echo '192.168.99.102 db.homework.lab db' >> /etc/hosts

SCRIPT

$set_app = <<SCRIPT

# 1. Create folder inside VM
sudo mkdir -p /app
sudo chown vagrant:vagrant /app

# 2. Copy local app/ to /app
sudo cp -r /vagrant/app/* /app

# 3. Install Python prerequisites
sudo apt-get update
sudo apt-get install python3.13-venv python3-pip -y

# 4. Create virtenv
cd /app
python3 -m venv .venv

# 5. Acticvate virt enviroment
source .venv/bin/activate

# 6. Install requirements
pip3 install -r requirements.txt

# 7. Rename .env.dev to .env
mv env.example .env

# 8. Run app detached from terminal
nohup /app/.venv/bin/python3 /app/app.py > /app/app.log 2>&1 &

SCRIPT

$set_db = <<SCRIPT

# 1. Install MariaDB
sudo apt update
sudo apt install -y mariadb-server mariadb-client

# 2. Configure MariaDB to listen on all interfaces
sudo sed -i 's/^bind-address\s*=.*/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf

# 3. Ensure MariaDB service start up on boot
sudo systemctl start mariadb
sudo systemctl enable mariadb

# 4. Restart MariaDB to apply configuration
sudo systemctl restart mariadb

# 5. Create app user
sudo mysql -e "CREATE USER IF NOT EXISTS 'app_user'@'localhost' IDENTIFIED BY 'Parolka-12345';"
sudo mysql -e "CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'Parolka-12345';"
sudo mysql -e "FLUSH PRIVILEGES;"

# 6. Initialize the database from db.sql
sudo mysql < /vagrant/db/db.sql

echo "MariaDB installed and database initialized!"

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "cdsn/debian13"
  config.vm.box_version = "1.0.0"

  config.vm.define "db" do |db|
    db.vm.hostname = "db.homework.lab"
    db.vm.network "private_network", ip: "192.168.99.102"
    db.vm.provision "shell", inline: $common
    db.vm.provision "shell", inline: $set_db
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "app.homework.lab"
    app.vm.network "private_network", ip: "192.168.99.101"
    app.vm.provision "shell", inline: $common
    app.vm.provision "shell", inline: $set_app
  end

end