global:
  registry: 192.168.56.12:5000
api:
  tag: latest
archiver:
  tag: latest
frontend:
  replicaCount: 3
  tag: latest
monitor:
  tag: latest
secrets:
  cli_password: AgCmEN7HLfNCm1eq6Ue7zYP60Mfa3eP0NqwAiR7Gg3yOX6OtykaQiazWu+EmVcd56OwF6/W4pTYWu2AV+9I02oh3vZXCRDgZI5Gdj+G3AxGljQI9fUGuZbOc2mDs4UBDZpJBvs+ZhNhNB8vhZKGG5VuahafTdSccEV8R9+Xe09/JaheOT40bFMjCBFqP1aSAmWeBteA4hpnyr8fSuRV+88YRs1Fky9ptonHmTyI0h5IdUOCkFzUrQo2D+EWfhal0eHj955BZ61FHnMBFdMgq/rk5IAkmOzaKSD8ezCuKZxz4O7/g7WzXArnR1Ov6PdF8bO6ZVYpDiMtKhB8Jq3XgPd6+ckMTooYJNzKim5pUZB/hLoTjIJKzjIrKbXat6b/KcKe2J9hGfRPqEVrf7FVlnELt3EkxqdFEP0b8PyFFlrfXvCueg5tMpTZHcQY7EmzC5ja5P6hiwvsawvy4o6XaB0rtGTn7b+2E93pD2ooG4peyrlU/COVhN5uHBC4qQABGxwLhYalA9lP122cftKvk7F5jYJX9s8IFLvVzxjdJ+qSQIpKDDKCMUMaM4P7YVWr0rL+2HKkBDaT1/EC+9g0cbMtTYlZKjAzCEJPKVSRflZAZNW5Gn904IxMpkJpqMu/mfgxgyMBkcQlCWHeDZ1yhL+kTXPskAiS81+aiIGgVrYA0p9cecbOq7KfLroDLwgrsvDIVgUet7wyJCDSKEbi0
  srv_password: AgDClFb5GILTO+xQ7mvEN/rMfo0saB5TyO85MB7l3zsKIxCLB6SLpJJXYEH2PsHu/Lm2ss4n70UZ2wtAOdQZg1fziXSIQ+6q6wZW2NMpSx82s7Z1sXHhz/ZtP959fN/Jzf8FF+fIslQQemBwJyivwg2kvmS2sMwtU+QMDGakO5tuoLU1XzKt16IckK+pstdGZAPoKuGyTXgDrngU8hW0RtfZ3rX08SnSPS/UmhlIILZrD7wrP3v6ISYQmUhV/sLvVRVbw2Zz9eP2+4u1hEiaGrmCIa0PaU7g+9lK5ppKJ/K4vGwe7tQa3ANFJpJcLYH5OMpBNjmGHqjoGSs7/WXf/pi9/qgQ6nEb170pW13hXQ5PK46eDGv7DX4ETLmp4d3WgbLa//icuio/Oo+HlKokXz/8WS7OCDjX/EaUGCKCU47BkEz/kgsqx5zBqOILazQ2CoN+ytmCpejksoJqlN94F6sTzpOPb3a2JDt7BKN2R0P/SOzteVP7CA+KxqNYd7QL3WbFap85Iu2YTe5SV/jwGTTW36Imfa3XshprPxq1IWmm5JOe06sJd2h5haKtusyFyV00qnYv0z7ADxIG1c84ARZ1yEMXqIwQlGrrkMQFH+ODRk/XvWPRtW4TG1IFLjzXa+ybXm4BYU1YZxp8WrQ42zs7bZ4w+mXjL0TLlh+jaIl9UHVNG1NowAdOXZkBOKqX1X6apPeYRTaKHjg7+I4oVmEJTISXYaXOSQ+V
