env:
  DOCKER_REGISTRY_URL: 192.168.99.101:5000
  DOCKER_IMAGE_NAME: task-manager-frontend

name: HTML/JS Frontend test and build image
run-name: ${{ gitea.actor }} is building the Frontend image
on:
  push:
    branches: [main]
    paths:
      - 'services/frontend/**' # The whole pipeline only runs if this folder changes
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Run End-To-End tests
      run: |
        cd services/frontend/tests
        ./smoke_test.sh

  test-pw:
    needs: test-e2e
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Set up Node
      uses: actions/setup-node@v5
      with:
        node-version: lts/*

    - name: Install dependencies
      run: |
        cd services/frontend/tests
        npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: |
        cd services/frontend/tests
        npx playwright test test_ui.spec.js

  build:
    needs: test-pw
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."192.168.99.101:5000"]
              http = true
              insecure = true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 10

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: ./services/frontend
          file: ./services/frontend/Dockerfile
          provenance: mode=max
          sbom: true
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
