pipeline {
    agent
    {
        label 'docker'
    }
    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.56.12:5000"
    }
    stages {
        stage('Test the API') {
            when { 
                changeset "services/api/**" 
            }
            agent {
                docker {
                    image 'python:3.12-slim'
                    // This ensures the container runs as the same user as Jenkins 
                    // to avoid permission issues with the workspace
                    args '-u root' 
                }
            }
            steps {
                sh '''
                # We are now INSIDE the python container
                # The workspace is automatically mounted at /home/jenkins/agent/workspace/...
                cd services/api
                pip install flask redis pytest
                python3 -m pytest tests/
                '''
            }
        }
        stage('Build the API') {
            when { 
                changeset "services/api/**" 
            }
            steps {
                sh '''
				cd services/api
				docker build -t ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-api:${IMAGE_TAG}
				'''
            }
        }
        stage('Build the Archiver') {
            when { 
                changeset "services/archiver/**" 
            }
            steps {
                sh '''
				cd services/archiver
				docker build -t ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG}
				'''
            }
        }
        stage('Build the Frontend') {
            when { 
                changeset "services/frontend/**" 
            }
            steps {
                sh '''
				cd services/frontend
				docker build -t ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG}
				'''
            }
        }
        stage('Build the Monitor') {
            when { 
                changeset "services/monitor/**" 
            }
            steps {
                sh '''
				cd services/monitor
				docker build -t ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-monitor:${IMAGE_TAG}
				'''
            }
        }
        stage('Clean')
        {
            steps
            {
                cleanWs()
            }
        }
    }
}
