name: Task Manager API Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check for secrets
        run: |
          curl -L https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz | tar xvzf - && \
          mv gitleaks /usr/local/bin/
          gitleaks dir ./services -v

      - name: Intall Hadolint
        run: |
          wget -O hadolint -q https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-linux-x86_64
          install -o root -g root -m 0755 hadolint /usr/local/bin/hadolint

      - name: Dockerfile linting
        run: |
          hadolint services/api/Dockerfile
          echo "Dockerfile is OK!"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd services/api
          pip install bandit

      - name: Python linting
        run: |
          cd services/api
          bandit app.py --skip B104

      - name: Docker Compose linting
        run: |
          wget -O dclint -q https://github.com/zavoloklom/docker-compose-linter/releases/download/v3.1.0/dclint-bullseye-amd64
          install -o root -g root -m 0755 dclint /usr/local/bin/dclint
          dclint infrastructure/

