name: Task Manager API Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd services/api
          pip install pytest redis flask

      - name: Run Unit Tests
        run: |
          cd services/api
          python3 -m pytest tests/test_app.py
