apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-be-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      service: be
  endpoints:
  - targetPort: 5000
    path: /metrics