name: Trivy Scan

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  schedule:
  - cron: "0 7 * * *"

jobs:
  check-api:
    uses: ./.gitea/workflows/trivy/trivy-check-api.yaml

  check-archiver:
    uses: ./.gitea/workflows/trivy/trivy-check-archiver.yaml

  check-frontend:
    uses: ./.gitea/workflows/trivy/trivy-check-frontend.yaml
 
  check-monitor:
    uses: ./.gitea/workflows/trivy/trivy-check-monitor.yaml
