apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .Release.Name }}-secret
spec:
  encryptedData:
    CLI_PASSWORD: {{ .Values.secrets.cli_password }}
    SRV_PASSWORD: {{ .Values.secrets.srv_password }}
   
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ .Release.Name }}-secret
    type: Opaque

