name: Task Manager Archiver

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches: [main]
    paths:
      - 'services/archiver/**'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.gitea/workflows/arc/1-lint.yaml

  test:
    needs: lint
    uses: ./.gitea/workflows/arc/2-test.yaml

  build:
    needs: test
    uses: ./.gitea/workflows/arc/3-build.yaml

  deploy:
    needs: build
    uses: ./.gitea/workflows/arc/4-deploy.yaml
    secrets: inherit
