pipeline {
    agent none

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }
    stages {
        stage('Test the Archiver') {
            agent { label 'docker' } 
            steps {
                script {
                    docker.image('eclipse-temurin:21-jdk').inside('-v maven-cache:/root/.m2') {
                        sh './mvnw test'
                    }
                }
            }
        }
        stage('Build the Archiver') {
            agent { label 'docker' }
            steps {
                sh '''
                # build image with current image tag
                docker build -t ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG} .
                
                # build image wuth 'latest' tag for current image
                docker tag ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG} ${REGISTRY_URL}/task-manager-archiver:latest
                
                docker push ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG}
                docker push ${REGISTRY_URL}/task-manager-archiver:latest
                '''
            }
        }
        stage('Clean') {
            agent { label 'docker' }
            steps {
                cleanWs()
            }
        }
    }
}