pipeline {
    agent
    {
        label 'docker'
    }
    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }
    stages {
        stage('Test the Archiver') {
            agent {
                docker {
                    image 'eclipse-temurin:21-jdk'
                    args '-v maven-cache:/root/.m2'
                    reuseNode true
                }
            }
            steps {
                sh './mvnw test'
            }
        }
        stage('Build the Archiver') {
            steps {
                sh '''
				cd services/archiver
				docker build -t ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-archiver:${IMAGE_TAG}
				'''
            }
        }
        stage('Clean')
        {
            steps
            {
                cleanWs()
            }
        }
    }
}
