name: Task Manager API Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Linting
        run: |
          echo '* Do some important linting stuff ...'
