name: Task Manager API Chagne

on:
  workflow_call:
  workflow_dispatch:

env:
  GITEA_URL: 192.168.56.12:3000
  REGISTRY_URL: 192.168.56.12:5000

jobs:
  change:
    runs-on: ubuntu-latest
    steps:
      - name: Update the image tag
        run: |
          # 0. Get the tag
          hash=${{ gitea.sha }}
          export API_TAG=${hash::10}

          # 1. Setup Auth and Clone Infra Repo
          git config --global user.name "Gitea CI"
          git config --global user.email "ci@gitea.local"
          
          git clone http://${{ secrets.REPO_USER }}:${{ secrets.REPO_PASS }}@${{ env.GITEA_URL }}/${{ secrets.REPO_USER }}/task-manager-infra.git
          cd task-manager-infra

          # 2. Update Version using yq
          yq -i "( .spec.containers[] | select(.name == \"api\") ).image = \"${{ env.REGISTRY_URL }}/task-manager-api:$API_TAG\"" manifests/api.yaml
          yq -i ".api.tag = \"$API_TAG\"" charts/task-manager/values.yaml
          yq -i "( .images[] | select(.name == \"${{ env.REGISTRY_URL }}/task-manager-api\") ).newTag = \"$API_TAG\"" kustomize/overlays/prd/kustomization.yaml

          # 3. Commit and Push back to Infra Repo
          git add .
          git commit -m "deploy: update api to $API_TAG from app repo"
          git push origin main
