pipeline {
    agent
    {
        label 'docker'
    }
    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }
    stages {
        stage('Test the Frontend Smoke Tests') {
            agent {
                docker {

                }
            }
            steps {
                sh '''
                cd tests/
                ./smoke_test.sh
                '''
            }
        }
        stage('Test the Frontend Playwright ') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.48.2-noble'
                    args '-u root --ipc=host'
                }
            }
            steps {
                sh '''
                cd tests/
                npm ci
                npx playwright test test_ui.spec.js
                '''
            }
        }
        stage('Build the Frontend') {
            steps {
                sh '''
				docker build -t ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG} .
				docker push ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG}
				'''
            }
        }
        stage('Clean')
        {
            steps
            {
                cleanWs()
            }
        }
    }
}
