pipeline {
    agent none

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REGISTRY_URL = "192.168.99.101:5000"
    }

    stages {
        stage('Test the Frontend Smoke Tests') {
            agent { label 'docker' }
            steps {
                script {
                    docker.image('node:20-slim').inside('-u root') {
                        sh '''
                        apt-get update && apt-get install -y curl
                        cd test/
                        chmod +x smoke_test.sh
                        ./smoke_test.sh
                        '''
                    }
                }
            }
        }

        stage('Test the Frontend Playwright') {
            agent { label 'docker' }
            steps {
                script {
                    docker.image('mcr.microsoft.com/playwright:v1.50.1-noble').inside('-u root --ipc=host') {
                        sh '''
                        cd test/
                        npm ci
                        npx playwright install --with-deps chromium
                        npx playwright test test_ui.spec.js
                        '''
                    }
                }
            }
        }

        stage('Build the Frontend') {
            agent { label 'docker' }
            steps {
                sh '''
                # build image with current image tag
                docker build -t ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG} .

                # tag image with 'latest' tag
                docker tag ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG} ${REGISTRY_URL}/task-manager-frontend:latest

                # push both tags
                docker push ${REGISTRY_URL}/task-manager-frontend:${IMAGE_TAG}
                docker push ${REGISTRY_URL}/task-manager-frontend:latest
                '''
            }
        }

        stage('Clean') {
            agent { label 'docker' }
            steps {
                cleanWs()
            }
        }
    }
}