#ENC[AES256_GCM,data:anhxgaw2xAzdwoR7ww==,iv:8lrjMdNy/XjkOZucUPYuOcVoNNBu6UIl/ujBwkp2X/I=,tag:nVkq7vGGop2u0qMGzh0lnQ==,type:comment]
cli_password: ENC[AES256_GCM,data:hS6w9MZe2VUaJO4cyQ==,iv:wkTFlS1fvsAiT11GeUJB3lKm7e0MIMjCWC6sKkAgi3U=,tag:MIZtvGFfwkHcuYFp6bC+WQ==,type:str]
srv_password: ENC[AES256_GCM,data:GHTcB/zLF8Mlyw85Hz6WiuN8cJ8bMl2mnA==,iv:PeJtmnPOB3DKMpRgS0a53kXCP8gqcYtlXUslOwarfg8=,tag:F6YgiQemVdvtTyhN/q4x6w==,type:str]
sops:
    age:
        - recipient: age1px73t0072ugacs3fc99xjevdxfje9xkqwjslf5v2xw38hu8kmelqrq8jft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeHJIVUgxeUZWR1NqT0FJ
            TE9oRmpKeDY5d3FxRU9CMm5jL3RKU2Z6aVYwCjN6VGI5cmZ6Z3ZtMDZUQUNxbjUr
            dU5KVVlvaE03Z1JwZEdTYlBBZXcvM2sKLS0tIG5ORWtSejhNUDIrNzdhbHRoTmJB
            OE9QZVljOE1mdWNKeFZhT01JNS9aN1kKT6APaaYaIVrmqnmM0z0/NdKKnM1ZhQDm
            lKc3/lkH72gyukm5slWdvxlbbbcMak7m9NofywTm6OkcfqHgUj6ycw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T14:04:20Z"
    mac: ENC[AES256_GCM,data:e1jfLZ1voRJnbo900WhIxX0tSe6gIAnwCX9e3aCKlfPSzSiGnZ5jAbD8sywQLrJSkKMu+0TMaHBiQA96D/s1l6zz370L/5HEDe6/NsC8RzKzXiW2vl9i6ZlidnqgcALPDtrJ0c9OD2m27GyDykoR4gw0W8DtVSD5YQI2RV6OC0k=,iv:7GSS66Dhv3rdcKKSYMj7JoU3y+sFGAAUddtAIQ74f90=,tag:c0AYthirG1wWJRcj5QHRDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
