Vagrant.configure("2") do |config|
  config.vm.box = "shekeriev/ubuntu-24.04"
  config.vm.box_version = "24.04.3.20260201"
  
  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker.homework.lab"
    docker.vm.network "private_network", ip: "192.168.99.101"
    docker.vm.synced_folder "vagrant/", "/vagrant"
    docker.vm.provision "shell", path: "scripts/add-hosts.sh"
    docker.vm.provision "shell", path: "scripts/install-prerequisites.sh"
    docker.vm.provision "shell", path: "scripts/install-docker.sh"
    docker.vm.provision "shell", path: "scripts/install-docker-registry.sh"
    docker.vm.provision "shell", path: "scripts/install-gitea.sh"
    docker.vm.provision "shell", path: "scripts/setup-gitea.sh"
    docker.vm.provider "virtualbox" do |vbox|
      vbox.name = "m3-docker"
      vbox.cpus = 2
      vbox.memory = 4096
    end
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins.homework.lab"
    jenkins.vm.network "private_network", ip: "192.168.99.102"
    jenkins.vm.synced_folder "vagrant/", "/vagrant"
    jenkins.vm.provision "shell", path: "scripts/add-hosts.sh"
    jenkins.vm.provision "shell", path: "scripts/install-prerequisites.sh"
    jenkins.vm.provision "shell", path: "scripts/install-jenkins.sh"
    jenkins.vm.provision "shell", path: "scripts/setup-jenkins.sh"
    jenkins.vm.provider "virtualbox" do |vbox|
      vbox.name = "m3-jenkins"
      vbox.cpus = 2
      vbox.memory = 4096
    end
  end

end