name: Task Manager Monitor Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check for secrets
        run: |
          curl -L https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz | tar xvzf - && \
          mv gitleaks /usr/local/bin/
          gitleaks dir ./services -v

      - name: Install hadolint
        run: |
          wget -O hadolint -q https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-linux-x86_64
          install -o root -g root -m 0755 hadolint /usr/local/bin/hadolint
          hadolint -v

      - name: Dockerfile linting
        run: |
          hadolint --ignore DL3018 services/monitor/Dockerfile
          echo $?

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: |
          wget -q https://github.com/golangci/golangci-lint/releases/download/v2.10.0/golangci-lint-2.10.0-linux-amd64.deb
          dpkg -i golangci-lint-2.10.0-linux-amd64.deb

      - name: Go linting
        run: |
          cat > ~/.golangci.yaml <<EOF
          version: "2"
          linters:
            default: all
            disable:
              - copyloopvar
              - intrange
              - wsl
              - exhaustruct
              - gochecknoglobals
              - depguard
          EOF
          cd services/monitor
          go mod tidy
          golangci-lint run --config=~/.golangci.yaml main.go

      - name: Docker Compose linting
        run: |
          wget -O dclint -q https://github.com/zavoloklom/docker-compose-linter/releases/download/v3.1.0/dclint-bullseye-amd64
          install -o root -g root -m 0755 dclint /usr/local/bin/dclint
          dclint infrastructure/
